# Generated by Django 4.0.2 on 2022-02-11 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('first_name', models.CharField(max_length=128)),
                ('last_name', models.CharField(max_length=128)),
                ('id', models.CharField(max_length=128, primary_key=True, serialize=False, unique=True)),
                ('location', models.CharField(max_length=128)),
            ],
        ),
    ]
