# Generated by Django 4.0.2 on 2022-02-12 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jpconnect', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Employee',
            new_name='Employees',
        ),
    ]
